# Example  .gitlab-ci.yml file
stages:
  - mavenbuild
  - maventest
  - androidbuild
  - androidtest

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd Backend
    - cd Backend
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd Backend
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar


android-build:
  image: gjandres/android-ci
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/MainApp/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - cd MainApp
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: gjandres/android-ci
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/MainApp/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - cd MainApp
    - ./gradlew test


