# Example  .gitlab-ci.yml file
stages:
  - mavenbuild
  - maventest
  - androidtry

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd Backend
    - cd Backend
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd Backend
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar


  

android-build: #this is another job
  image: javiersantos/android-ci:latest      # this is a directive to DOCKER
  stage: androidtry
  tags:
   - android_tag         #this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew assemble
